Repository BootTalk-Service/boot-talk-back, pull requests merged in 2025-04, with the labels that each got.

#24 feat : 부트캠프 중복 등록 방지 및 존재하지 않는 카테고리 출력 로그 작성
  boottalk/src/main/java/com/icandoit/boottalk/batch/scheduler/BootcampFetchScheduler.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/BootcampEmploy24Response.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/BootcampCategoryType.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/TrainingCenter.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/BootcampRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/Employ24ApiService.java
Labels: enhancement

#28 feat: 유저엔티티에 resourceUserId 필드값 추가, SignUpService 에서 resourceUserId를 …
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/entity/User.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/form/SignUpForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/form/UpdateForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/repository/UserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/type/DesiredCareer.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/ManageService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/SignUpService.java
Labels: enhancement

#30 Feat/course : course (훈련 번호) 도입 및 관련 도메인 및 서비스 로직 수정
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/Bootcamp.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/Course.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/BootcampRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/CourseRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampService.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/Employ24ApiService.java
  boottalk/src/main/java/com/icandoit/boottalk/review/controller/ReviewController.java
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/review/entity/Review.java
  boottalk/src/main/java/com/icandoit/boottalk/review/repository/ReviewRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/review/service/ReviewService.java
Labels: enhancement

#34 Feat/bootcmap reviews by course
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatInfoResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatInfoRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/review/controller/ReviewController.java
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewCreateRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/review/dto/ReviewUpdateRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/review/entity/Review.java
  boottalk/src/main/java/com/icandoit/boottalk/review/repository/ReviewRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/review/service/ReviewService.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewServiceTest.java
Labels: enhancement

#39 Feat/social login 기능 구현
  boottalk/build.gradle
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/CustomOAuth2User.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/NaverResponse.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/UserAuthDto.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/UserRole.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtFilter.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtProvider.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/CustomClientRegistrationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/CustomSuccessHandler.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/SocialClientRegistration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/service/CustomUserService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/entity/User.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/repository/UserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/SignUpService.java
Labels: enhancement

#42 Feat/coffeechat 시간 변경 및 예정된 커피챗 목록 조회 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatApplicationController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatQueryController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatInfoApprovedDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatInfoRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatInfoResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatListDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeListDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/CoffeeChatInfo.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/CoffeeChatTime.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/enums/MentorType.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatApplicationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatInfoRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatQueryRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatTimeRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatQueryService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoServiceTest.java
Labels: enhancement

#45 Feat/토큰 발급 테스트용 로그인, 회원가입
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/repository/UserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/UserTestController.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/form/TestSignUpForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/service/UserTestService.java
Labels: enhancement

#43 Feat/review paging 기능 구현
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/CategoryController.java
  boottalk/src/main/java/com/icandoit/boottalk/review/controller/ReviewController.java
  boottalk/src/main/java/com/icandoit/boottalk/review/repository/ReviewRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/review/service/ReviewService.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewConcurrencyTest.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewServiceTest.java
Labels: enhancement

#48 Feat/coffeechat 커피챗 멘토 시간 등록 API 포맷팅 변경 및 중복 생성 방지
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatApplicationResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeMapDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/CoffeeChatTime.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatTimeRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/converter/CoffeeChatTimeConverter.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
Labels: enhancement

#49 Feat/bootcamp paging 부트캠프 전체 조회 및 검색 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampController.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/BootcampResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/BootcampCategoryType.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/Course.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/BootcampQueryRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampService.java
  boottalk/src/test/java/com/icandoit/boottalk/bootcamp/service/BootcampServiceTest.java
Labels: enhancement

#52 Feat/ coffeechatTime 조회 API 추가 및 변경
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
Labels: enhancement

#54 Feat/ point history 생성 시 트랜잭션으로 관리, 비관적 락 사용
  boottalk/src/main/java/com/icandoit/boottalk/point_history/controller/PointHistoryController.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/repository/PointHistoryRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/service/CreatePointHistoryService.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/service/SearchPointHistoryService.java
Labels: enhancement

#56 Feat/커피챗 신청 시 동일 시간대 중복 신청 방지 기능 및 테스트 추가
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatApplicationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationService.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationConcurrencyTest.java
Labels: enhancement, test

#68 feat : 리뷰 컨트롤러 인증(authorization) 추가
  boottalk/src/main/java/com/icandoit/boottalk/review/controller/ReviewController.java
Labels: enhancement

#73 Feat/user-my-certification: 내 수료 인증 정보 조회 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampCertificationController.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/CertificationUpdateRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/GetCertificationInfoDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/GetCertificationResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/GetPendingCertificationResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/entity/BootcampCertification.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/BootcampCertificationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampCertificationService.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/ManageController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserInfoDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/NotificationTestController.java
Labels: enhancement

#74 Feat/chat 1:1 채팅 API + 웹소켓 API 기초 구현
  boottalk/build.gradle
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/WebSocketConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatRoomController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatRoomCreateResponse.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatRoomEnterDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatRoomResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/MessageRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/MessageResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/ChatRoom.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/Message.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/enums/MessageType.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/ChatRoomRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/MessageRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatRoomService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/MessageFactoryService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/util/SystemMessageUtil.java
Labels: enhancement

#75 Feat/관리자 권한 설정을 위한 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/service/CustomUserService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/entity/User.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/UserTestController.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/service/UserTestService.java
Labels: enhancement

#80 Feat/소셜 로그인 프론트 엔드 연동을 위한 설정값 추가
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtFilter.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/CustomSuccessHandler.java
Labels: enhancement

#81 Feat/상단 내비 바 사용자 정보 표시를 위한 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/repository/PointHistoryRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/service/CreatePointHistoryService.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/CustomOAuth2User.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/UserAuthDto.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtProvider.java
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/ManageController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/NaviUserInfoDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/UserTestController.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/service/UserTestService.java
Labels: enhancement

#82 feat : CoffeeChatInfo + Times 복합 API 추가
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatRegisterController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRegisterRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRegisterResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatRegisterService.java
Labels: enhancement

#84 feat : 부트캠프 저장 및 알림 전송을 위한 redis 사용
  boottalk/build.gradle
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/BootcampBatchJobConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/QuartzFetchConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/QuartzFetchTriggersConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/QuartzNotificationConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/scheduler/FetchBootcampQuartzJob.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/scheduler/NotificationQuartzJob.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/Employ24ApiService.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/RedisService.java
  boottalk/src/main/java/com/icandoit/boottalk/common/config/RedisConfig.java
  boottalk/src/main/resources/application.yml
Labels: enhancement

#86 Feat/review certification
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/repository/BootcampCertificationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/review/service/ReviewService.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewServiceTest.java
Labels: enhancement, test

#87 feat : certification 조회, 수정 관리자 권한 추가
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampCertificationController.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampCertificationService.java
Labels: enhancement

#88 feat: 커피챗 신청 가능 시간 목록 조회
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatApplicationController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/AvailableChatTimeDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatApplicationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatTimeRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
Labels: enhancement

#89 feat: 커피챗 정보/커피챗 신청 상세 조회 추가
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatApplicationController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatInfoRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
Labels: enhancement

#93 Feat: 커피챗 자동 환불 기능 및 테스트 추가
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/CoffeeChatApplication.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/enums/StatusType.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatApplicationRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/scheduler/CoffeeChatRefundScheduler.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatRefundService.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/type/EventType.java
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/scheduler/CoffeeChatRefundServiceTest.java
Labels: enhancement, test

#94 fix: 커피챗 신청 관련 테스트 수정 (CoffeeChatApplicationServiceTest, CoffeeChatApplicationServiceIntegrationTest)
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationServiceIntegrationTest.java
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationServiceTest.java
Labels: test

#95 Feat/상단 내비 바 포인트 실시간 반영 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/notification/controller/NotificationController.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/controller/SseController.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/event/CreatePointEvent.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/event/SendNotificationEvent.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/repository/SseEmitterRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/NotificationService.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/SseEmitterService.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/controller/PointHistoryController.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/service/CreatePointHistoryService.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/NotificationTestController.java
Labels: enhancement

#97 Feat/notification new bootcamp 부트캠프 개설시 알림 전송 기능
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/QuartzFetchTriggersConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/config/QuartzNotificationConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/batch/scheduler/NotificationQuartzJob.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/config/RestTemplateConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/RedisService.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/dto/NotificationRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/type/NotificationType.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/repository/UserRepository.java
  boottalk/src/test/java/com/icandoit/boottalk/batch/config/BootcampBatchJobConfigTest.java
  boottalk/src/test/java/com/icandoit/boottalk/batch/scheduler/FetchBootcampQuartzJobTest.java
Labels: enhancement, test

#98 Fix/bootcamp detail response : BootcampResponseDto 추가 및 JobType 추가
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampController.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/BootcampDetailResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/entity/enums/JobType.java
Labels: enhancement

#99 Feat/review point : 리뷰 생성 삭제시 포인트 적립, 회수 기능
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/entity/PointHistory.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/type/EventType.java
  boottalk/src/main/java/com/icandoit/boottalk/review/service/ReviewService.java
  boottalk/src/test/java/com/icandoit/boottalk/bootcamp/service/BootcampServiceTest.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewConcurrencyTest.java
  boottalk/src/test/java/com/icandoit/boottalk/review/service/ReviewServiceTest.java
Labels: enhancement, test

#100 Feat: CoffeeChatInfo + Times API 통합 -> CoffeeChatController로 조회, 수정, 삭제 요청 관리
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatRegisterController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatTimeController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRegisterRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRegisterResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatTimeMapDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatRegisterService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
Labels: enhancement

#101 refactor: 커피챗 필터링 조회 시 페이징 응답을 Page -> PagedResponseDto 로 통일
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/controller/CoffeeChatQueryController.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/repository/CoffeeChatQueryRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatQueryService.java
  boottalk/src/test/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoServiceTest.java
Labels: refactor

#102 Feat/도메인에 따른 동적 url 반환을 위한 기능 추가
  boottalk/src/main/java/com/icandoit/boottalk/notification/controller/NotificationController.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/dto/NotificationRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/dto/NotificationResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/entity/Notification.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/event/NotificationEvent.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/NotificationService.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/SseEmitterService.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/type/NotificationType.java
  boottalk/src/main/resources/application.yml
Labels: enhancement

#106 refactor : Bootcamp 관련 collect() 함수를 .toList()로 refactor
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/CategoryController.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/dto/BootcampResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampCertificationService.java
Labels: refactor

#108 feat : 부트캠프 수료 승인/거절 시 알림 발송 로직 구현
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/BootcampCertificationService.java
Labels: enhancement

#110 refactor : coffeeChat - request,response dto 변경에 따른 로직 수정
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/AvailableChatTimeDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/dto/CoffeeChatResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/converter/CoffeeChatTimeConverter.java
Labels: refactor

#111 refactor : 내 정보 조회시 currentPoint 도 응답 가능하도록 dto 및 로직 수정
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/ManageController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserInfoDto.java
Labels: refactor

#109 Feat/chat 채팅 기능 개선 및 Redis / 인증 기능 추가
  boottalk/build.gradle
  boottalk/src/main/java/com/icandoit/boottalk/common/config/RedisConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtProvider.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/common/RedisKeyPrefix.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/WebSocketConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/WebSocketHandshakeInterceptor.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatRoomController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatMessageResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatRoomEnterDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatRoomResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatUserDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/MessageResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/stompDto/ChatMessageRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/stompDto/ChatTypingRequestDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/stompDto/ChatTypingResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/ChatMessage.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/ChatRoom.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/entity/ChatRoomStatus.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/ChatMessageRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/ChatRoomStatusRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/MessageRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatMessageRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatRoomRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatUserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatMessageSchedulerService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatRoomService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/MessageFactoryService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/ChatMessageSender.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/ChatRoomStatusUpdater.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/MessageLoader.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/util/SystemMessageUtil.java
Labels: enhancement

#115 refactor: 커피챗 공통 메소드 분리 및 수신 목록 조회 시 커피챗 정보 없을 경우 200 응답으로 처리
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatApplicationService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatCommonService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatReceivedService.java
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
Labels: refactor

#117 Refactor/empoloy24 service
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/service/Employ24ApiService.java
Labels: refactor

#118 refactor : user 관련 부분 들여쓰기 수정
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/AddUserInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/AddUserInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/ManageService.java
Labels: refactor

#112 Fix/Security Config CORS 추가
  boottalk/src/main/java/com/icandoit/boottalk/common/config/CorsConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/dto/NaverResponse.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtFilter.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/CustomSuccessHandler.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/SocialClientRegistration.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/entity/User.java
Labels: enhancement

#124 refactor : NotificationType 의 url 수정
  boottalk/src/main/java/com/icandoit/boottalk/notification/type/NotificationType.java
Labels: refactor

#126 Feat & Fix : 채팅 기능 최종 구현 ( 리팩토링 & 버그 수정 & Message알림 기능추가)
  boottalk/src/main/java/com/icandoit/boottalk/coffeeChat/service/CoffeeChatTimeService.java
  boottalk/src/main/java/com/icandoit/boottalk/common/RedisKeyPrefix.java
  boottalk/src/main/java/com/icandoit/boottalk/common/config/RedisConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/jwt/JwtFilter.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/oauth2/CustomSuccessHandler.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/AuthHandshakeInterceptor.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/WebSocketConfig.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/WebSocketHandshakeInterceptor.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/ChatMessageResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatMessageRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatRoomRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatUserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/MessageLoader.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/WebSocketEventListener.java
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/AddUserInfoController.java
Labels: enhancement, fix

#127 fix : typing 시 요구하는 request, response 수정
  boottalk/src/main/java/com/icandoit/boottalk/notification/type/NotificationType.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/dto/stompDto/ChatTypingResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
Labels: fix

#128 fix : Notification sse GetMapping 으로 수정
  boottalk/src/main/java/com/icandoit/boottalk/notification/controller/SseController.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/SseEmitterService.java
Labels: fix

#132 fix : 유저가 채팅에서 나갔을 시에 userId 가 반환되지 않던 오류 수정
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/WebSocketEventListener.java
Labels: fix

#134 Refactor/notification base url remove
  boottalk/src/main/java/com/icandoit/boottalk/notification/dto/NotificationResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/NotificationService.java
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/SseEmitterService.java
  boottalk/src/main/resources/application.yml
Labels: refactor

#135 fix:최근 알림 읽음 처리를 위한 jpa 쿼리 수정
  boottalk/src/main/java/com/icandoit/boottalk/notification/repository/NotificationRepository.java
Labels: fix

#136 fix : 대량 알림 전송 시 서버 부하를 줄이기 위해 이벤트 발송을 비동기 처리 구조로 전환
  boottalk/src/main/java/com/icandoit/boottalk/batch/scheduler/NotificationQuartzJob.java
  boottalk/src/test/java/com/icandoit/boottalk/batch/scheduler/FetchBootcampQuartzJobTest.java
Labels: fix

#139 Refactor/ 사용자 인증 시 쿠키 사용으로 변경
  boottalk/src/main/java/com/icandoit/boottalk/notification/controller/SseController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/config/AuthHandshakeInterceptor.java
Labels: refactor

#141 Fix/ 이벤트 리스너 @TransactionalEventListener에 옵션추가
  boottalk/src/main/java/com/icandoit/boottalk/notification/service/SseEmitterService.java
Labels: fix

#142 Feat/chatroom scheduling enhancement : Quartz Job 개선
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatRoomController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/repository/RedisChatUserRepository.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/scheduler/ChatQuartzSchedulerService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/scheduler/EndCoffeeChatJob.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/scheduler/StartCoffeeChatJob.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatRoomService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
Labels: enhancement

#144 Fix/ 로그아웃 시 쿠키에 담긴 토큰 제거
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
Labels: fix

#143 Refactor/ 사용자 인증, 권한 확인 실패 시 SecurityFilter에서 커스텀 에러로 처리
  boottalk/src/main/java/com/icandoit/boottalk/bootcamp/controller/BootcampCertificationController.java
  boottalk/src/main/java/com/icandoit/boottalk/libs/exception/ErrorCode.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/SecurityConfiguration.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/exception/CustomAccessDeniedException.java
  boottalk/src/main/java/com/icandoit/boottalk/social_login/config/exception/CustomAuthenticationEntryPoint.java
Labels: refactor

#146 fix : userName이 멘토 이름으로 고정 되어있던 부분 수정
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/controller/ChatWebSocketController.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/ChatWebsocketService.java
  boottalk/src/main/java/com/icandoit/boottalk/stomp_chat/service/component/ChatMessageSender.java
Labels: fix

#147 Fix/사용자 정보 수정 시 desiredCareer 타입 처리
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/entity/User.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/form/UpdateForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/AddUserInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/ManageService.java
Labels: fix

#152 Refactor/Dto 이름 통일
  boottalk/src/main/java/com/icandoit/boottalk/point_history/controller/PointHistoryController.java
  boottalk/src/main/java/com/icandoit/boottalk/point_history/domain/form/PointHistoryForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/AddUserInfoController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/controller/ManageController.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserInfoDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserResponseDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/domain/dto/UserUpdateDto.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/AddUserInfoService.java
  boottalk/src/main/java/com/icandoit/boottalk/user/service/ManageService.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/controller/UserTestController.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/form/TestSignUpForm.java
  boottalk/src/main/java/com/icandoit/boottalk/user_test/service/UserTestService.java
Labels: refactor
